from enum import Enum


class Permission(str, Enum):
    QUICK_SALE = "QUICK_SALE"

    WARRANTY_VIEW = "WARRANTY_VIEW"

    DAILY_LEDGER_VIEW = "DAILY_LEDGER_VIEW"

    MECHANIC_LEDGER_VIEW = "MECHANIC_LEDGER_VIEW"
    MECHANIC_TRANSACTION_CREATE = "MECHANIC_TRANSACTION_CREATE"

    SCRAP_PURCHASE = "SCRAP_PURCHASE"
    SCRAP_SALE = "SCRAP_SALE"

    BATTERY_SALE = "BATTERY_SALE"

    INVOICE = "INVOICE"
    PAYMENT = "PAYMENT"

    PRODUCT = "PRODUCT"
    INVENTORY = "INVENTORY"

    VENDOR_PURCHASE = "VENDOR_PURCHASE"

    REPORTS = "REPORTS"

    USERS = "USERS"
    SETTINGS = "SETTINGS"
